### ISSUE TITLE
example-NS MethodError

### ISSUE THREAD

**Issue by bennn** [paralab/Finch#2]
The NS example here has the same problem as the femshop version (<https://github.com/paralab/femshop/issues/15>):

```
$ julia --version
julia version 1.8.0
$ julia example-NS.jl 
ERROR: LoadError: MethodError: no method matching nonlinear_solve(::Vector{Variable}, ::Vector{Variable}, ::GenFunction, ::GenFunction, ::Finch.Stepper; assemble_func=nothing)
Closest candidates are:
  nonlinear_solve(::Any, ::Any, ::Any, ::Any, ::Any; assemble_loops) at ~/.julia/packages/Finch/I3WJX/src/CGSolver.jl:316 got unsupported keyword argument "assemble_func"
  nonlinear_solve(::Any, ::Any, ::Any, ::Any) at ~/.julia/packages/Finch/I3WJX/src/CGSolver.jl:316 got unsupported keyword argument "assemble_func"
Stacktrace:
 [1] kwerr(::NamedTuple{(:assemble_func,), Tuple{Nothing}}, ::Function, ::Vector{Variable}, ::Vector{Variable}, ::GenFunction, ::GenFunction, ::Finch.Stepper)
   @ Base ./error.jl:165
 [2] macro expansion
   @ ./timing.jl:383 [inlined]
 [3] solve(var::Vector{Variable}, nlvar::Vector{Variable}; nonlinear::Bool)
   @ Finch ~/.julia/packages/Finch/I3WJX/src/finch_interface.jl:1290
 [4] top-level scope
   @ ~/code/uu/fpx/FloatTracker.jl/example/finch/example-NS.jl:89
in expression starting at example-NS.jl:89
```

Should `finch_interface.jl` use the keyword `assemble_loops` instead of `assemble_func`?

**Comment by ericheisler** [comment]
There were a few updates that were not applied to the nonlinear solver because it severely needs to be redone. We are in the middle of a major revision and once that is complete this whole nonlinear solver will not exist. Nonlinear problems will be handled directly in the generated code, so there isn't much sense in depending on this version. 
I patched this anyway so that it works for this example.
See the new-IR branch for a more recent version of Finch, but some of the existing examples won't work with it yet. Sorry.

**Comment by bennn** [comment]
👍  thanks for explaining
